<?php
// Exit if accessed directly.
if (!defined('ABSPATH')) {
    exit;
}

return array(
    'authentication' => array(
        'title'    => __("Authentication", "enginethemes"),
        'slug'     => 'authentication',
        'type'     => 'section',
        'template' => array(
            'user-account-page' => array(
                'label'       => __("User Account Page", "enginethemes"),
                'description' => __("Choose a page to display as User Account Page", "enginethemes"),
                'slug'        => 'user-account-page',
                'type'        => 'select',
                'name'        => 'me_user_account_page_id',
                'data'        => marketengine_get_list_of_page(),
                'template'    => array(),
            ),
            'seller-profile-page' => array(
                'label'       => __("Seller Profile Page", "enginethemes"),
                'description' => __("Choose a page to display as Seller Profile Page", "enginethemes"),
                'slug'        => 'seller-profile-page',
                'type'        => 'select',
                'name'        => 'me_seller_profile_page_id',
                'data'        => marketengine_get_list_of_page(),
                'template'    => array(),
            ),
            'user-email-confirmation' => array(
                'label'       => __("Email Confirmation", "enginethemes"),
                'description' => __("", "enginethemes"),
                'slug'        => 'user-email-confirmation',
                'type'        => 'switch',
                'name'        => 'user-email-confirmation',
                'template'    => array(),
            ),
            'user-account-endpoint' => array(
                'label'       => __("Endpoint Setting", "enginethemes"),
                'description' => __("Choose a page to display as User Account Page", "enginethemes"),
                'slug'        => 'user-account-endpoint',
                'type'        => 'multi_field',
                'name'        => 'user-account-endpoint',
                'data'        => marketengine_get_list_of_page(),
                'template'    => array(
                    'ep-edit-profile' => array(
                        'label'       => __("Edit Profile", "enginethemes"),
                        'slug'        => 'ep-edit-profile',
                        'type'        => 'textbox',
                        'name'        => 'ep_edit_profile',
                        'placeholder' => 'edit-profile',
                        'template'    => array(),
                    ),
                    'ep-change-password' => array(
                        'label'       => __("Change Password", "enginethemes"),
                        'slug'        => 'ep-change-password',
                        'type'        => 'textbox',
                        'name'        => 'ep_change_password',
                        'placeholder' => 'change-password',
                        'template'    => array(),
                    ),
                    'ep-listings' => array(
                        'label'       => __("My Listings", "enginethemes"),
                        'slug'        => 'ep-listings',
                        'type'        => 'textbox',
                        'name'        => 'ep_listings',
                        'placeholder' => 'listings',
                        'template'    => array(),
                    ),
                    'ep-edit-listing' => array(
                        'label'       => __("Edit Listing", "enginethemes"),
                        'slug'        => 'ep-listing-id',
                        'type'        => 'textbox',
                        'name'        => 'ep_listing_id',
                        'placeholder' => 'edit-listing',
                        'template'    => array(),
                    ),
                    'ep-orders' => array(
                        'label'       => __("Orders", "enginethemes"),
                        'slug'        => 'ep-orders',
                        'type'        => 'textbox',
                        'name'        => 'ep_orders',
                        'placeholder' => 'orders',
                        'template'    => array(),
                    ),
                    'ep-order' => array(
                        'label'       => __("Order", "enginethemes"),
                        'slug'        => 'ep-orderid',
                        'type'        => 'textbox',
                        'name'        => 'ep_orderid',
                        'placeholder' => 'order',
                        'template'    => array(),
                    ),
                    'ep-purchases' => array(
                        'label'       => __("Purchases", "enginethemes"),
                        'slug'        => 'ep-purchases',
                        'type'        => 'textbox',
                        'name'        => 'ep_purchases',
                        'placeholder' => 'purchases',
                        'template'    => array(),
                    ),
                    'ep-forgot-password' => array(
                        'label'       => __("Forgot Password", "enginethemes"),
                        'slug'        => 'ep-forgot-password',
                        'type'        => 'textbox',
                        'name'        => 'ep_forgot_password',
                        'placeholder' => 'forgot-password',
                        'template'    => array(),
                    ),
                    'ep-reset-password' => array(
                        'label'       => __("Reset Password", "enginethemes"),
                        'slug'        => 'ep-reset-password',
                        'type'        => 'textbox',
                        'name'        => 'ep_reset_password',
                        'placeholder' => 'reset-password',
                        'template'    => array(),
                    ),
                    'ep-register' => array(
                        'label'       => __("Register", "enginethemes"),
                        'slug'        => 'ep-register',
                        'type'        => 'textbox',
                        'name'        => 'ep_register',
                        'placeholder' => 'register',
                        'template'    => array(),
                    ),
                ),
            ),
        ),
    ),
);